"""Versioned, seeded evaluation report (FR-A5, §10) — markdown + figures."""
from __future__ import annotations

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt  # noqa: E402
import pandas as pd  # noqa: E402

from . import config  # noqa: E402

BRAND = "#e86020"
BASELINE = "#5f6368"
RANDOM = "#b0b3b8"


def _fig_qini(points: dict, path) -> None:
    fig, ax = plt.subplots(figsize=(6, 4))
    qx = [p["x"] for p in points["qini"]]
    qy = [p["y"] for p in points["qini"]]
    ax.plot(qx, qy, color=BRAND, lw=2.5, label="Uplift model (Qini)")
    ax.plot([0, 1], [0, qy[-1] if qy else 0], color=RANDOM, ls="--", label="Random")
    ax.set_xlabel("Fraction of population targeted")
    ax.set_ylabel("Cumulative incremental outcomes")
    ax.set_title("Qini curve")
    ax.legend()
    fig.tight_layout()
    fig.savefig(path, dpi=120)
    plt.close(fig)


def _fig_sweep(sweep: list[dict], path) -> None:
    df = pd.DataFrame(sweep)
    fig, ax = plt.subplots(figsize=(6, 4))
    ax.plot(df["budget"], df["uplift"], color=BRAND, lw=2.5, label="Uplift targeting")
    ax.plot(df["budget"], df["propensity"], color=BASELINE, lw=2, label="Propensity")
    ax.plot(df["budget"], df["random"], color=RANDOM, lw=2, ls="--", label="Random")
    ax.set_xlabel("Budget (customers contacted)")
    ax.set_ylabel("Incremental profit")
    ax.set_title("Incremental profit vs budget (headline, AC-3)")
    ax.legend()
    fig.tight_layout()
    fig.savefig(path, dpi=120)
    plt.close(fig)


def _fig_decile(deciles: pd.DataFrame, path) -> None:
    fig, ax = plt.subplots(figsize=(6, 4))
    ax.bar(range(1, len(deciles) + 1), deciles["uplift"], color=BRAND)
    ax.set_xlabel("Decile (1 = highest predicted uplift)")
    ax.set_ylabel("Actual incremental response")
    ax.set_title("Uplift by decile (AC-2)")
    ax.axhline(0, color=BASELINE, lw=0.8)
    fig.tight_layout()
    fig.savefig(path, dpi=120)
    plt.close(fig)


def write_report(
    dataset: str,
    metrics: dict,
    balance_df: pd.DataFrame,
    deciles: pd.DataFrame,
    calibration: pd.DataFrame,
    qini_points: dict,
    sweep: list[dict],
) -> None:
    d = config.report_dir(dataset)
    _fig_qini(qini_points, d / "qini.png")
    _fig_sweep(sweep, d / "profit_vs_budget.png")
    _fig_decile(deciles, d / "uplift_by_decile.png")

    best = metrics["best_learner"]
    rows = "\n".join(
        f"| {k} | {v['qini']:.4f} | {v['auuc']:.4f} | "
        f"{'✅' if v['ranks_correctly'] else '⚠️'} |"
        for k, v in metrics["learners"].items()
    )
    dem = metrics["decision_demo"]
    dec_tbl = deciles[["percentile", "n_treatment", "n_control", "uplift"]].to_markdown(index=False) \
        if "n_treatment" in deciles.columns else deciles.to_markdown(index=False)

    md = f"""# UpliftIQ — Evaluation Report · `{dataset}`

*Seeded run (seed = {metrics['seed']}). Reproduce with*
`python -m pipeline.run --dataset {dataset} --seed {metrics['seed']}`.

- **Rows:** {metrics['n_rows']:,} (holdout {metrics['n_holdout']:,})
- **Best learner (by Qini):** **{best}**
- **Elapsed:** {metrics['elapsed_sec']}s

## 1. Experiment balance (FR-A2)
Treatment ratio **{metrics['balance']['treatment_ratio']:.3f}** · max |SMD|
**{metrics['balance']['max_abs_smd']:.3f}** · flagged features
**{metrics['balance']['n_flagged']}** · randomization
**{'OK' if metrics['balance']['passed'] else 'CHECK'}**.

## 2. Model benchmark (FR-A3–A5)
Evaluated on a randomized holdout with **uplift-appropriate metrics only**.

| Learner | Qini | AUUC | Ranks uplift? |
|---|---|---|---|
{rows}

> **Why not accuracy/AUC?** {metrics['why_not_accuracy']}

![Qini curve](qini.png)

## 3. Uplift by decile (AC-2)
Top deciles should show materially higher actual incremental response than the
bottom — evidence the model *ranks* uplift, not just outcome.

![Uplift by decile](uplift_by_decile.png)

{dec_tbl}

## 4. Calibration
Predicted vs observed uplift per bin.

{calibration.to_markdown(index=False)}

## 5. Decision benchmark — the headline (AC-3)
At budget **{dem['budget']:,}** (cost {dem['cost_per_contact']}/contact,
value {dem['value_per_conversion']}/conversion):

| Policy | Incremental conversions | Incremental profit |
|---|---|---|
| **Uplift** | {dem['uplift']['incremental_conversions']:.1f} | **{dem['uplift']['incremental_profit']:.1f}** |
| Propensity | {dem['propensity']['incremental_conversions']:.1f} | {dem['propensity']['incremental_profit']:.1f} |
| Random | {dem['random']['incremental_conversions']:.1f} | {dem['random']['incremental_profit']:.1f} |

**Profit lift of uplift vs propensity: {dem['profit_lift_vs_propensity']:.1f}**
· vs random: {dem['profit_lift_vs_random']:.1f}.

![Profit vs budget](profit_vs_budget.png)

---
*Generated by `pipeline/report.py`. All figures regenerate from the seeded pipeline (FR-D3).*
"""
    (d / "report.md").write_text(md, encoding="utf-8")
