"""FR-C5 — LLM segment explainer (Gemini), with a templated fallback.

When GEMINI_API_KEY is set, a short plain-language explanation of a segment is
generated by Gemini, grounded in the supplied metrics + feature drivers. When
no key is present a deterministic templated explanation is returned instead, so
the endpoint always works.
"""
from __future__ import annotations

from pipeline import config

_SEGMENT_FACTS = {
    "Persuadable": "converts only because of the campaign (uplift > 0) — the gold segment to target.",
    "Sure Thing": "converts with or without contact — targeting wastes the incentive.",
    "Lost Cause": "almost never converts — targeting wastes the contact.",
    "Sleeping Dog": "contact *lowers* conversion (uplift < 0) — must never be targeted.",
}


def _fallback(segment: str, count: int, total: int, drivers: list[str] | None) -> str:
    fact = _SEGMENT_FACTS.get(segment, "a customer group defined by its treatment effect.")
    share = f"{(100*count/total):.1f}%" if total else "n/a"
    drv = ""
    if drivers:
        drv = " Key drivers: " + ", ".join(drivers[:5]) + "."
    return (
        f"{segment} ({count:,} customers, {share} of the audience) — this group {fact}{drv} "
        f"Recommendation: {'prioritise budget here' if segment == 'Persuadable' else 'exclude from this campaign'}."
    )


def explain_segment(
    segment: str,
    count: int,
    total: int,
    drivers: list[str] | None = None,
    metrics: dict | None = None,
) -> dict:
    """Return {text, source} where source is 'gemini' or 'fallback'."""
    if not config.gemini_enabled():
        return {"text": _fallback(segment, count, total, drivers), "source": "fallback"}

    try:
        import google.generativeai as genai

        genai.configure(api_key=config.GEMINI_API_KEY)
        model = genai.GenerativeModel(config.GEMINI_MODEL)
        prompt = (
            "You are a marketing analytics assistant for an uplift-modeling decision engine. "
            "Explain, in 2-3 concise sentences for a marketing manager, the following uplift "
            "segment and what to do about it. Be grounded only in the data provided; do not invent numbers.\n\n"
            f"Segment: {segment}\n"
            f"Definition: {_SEGMENT_FACTS.get(segment, 'unknown')}\n"
            f"Customers in segment: {count} of {total}\n"
            f"Top feature drivers: {', '.join(drivers or []) or 'n/a'}\n"
            f"Model metrics: {metrics or 'n/a'}\n"
        )
        resp = model.generate_content(prompt)
        text = (getattr(resp, "text", None) or "").strip()
        if not text:
            raise ValueError("empty response")
        return {"text": text, "source": "gemini"}
    except Exception as exc:  # pragma: no cover - network guard
        return {
            "text": _fallback(segment, count, total, drivers),
            "source": f"fallback (gemini error: {exc})",
        }
